openapi: 3.0.0
info:
  title: Pet API
  description: This API provides endpoints to manage pets.
  version: 1.0.0

paths:
  /pets:
    get:
      description: Get all pets.
      operationId: getPets
      responses:
        200:
          description: A list of pets.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Pet"
    post:
      description: Create a new pet.
      operationId: addPet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
      responses:
        200:
          description: The created pet.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
  /pets/{id}:
    get:
      description: Get a pet by ID.
      operationId: getPetById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: A pet.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
    put:
      description: Update a pet by ID.
      operationId: updatePet
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
      responses:
        200:
          description: The updated pet.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
    delete:
      description: Delete a pet by ID.
      operationId: deletePet
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: The pet was deleted.

components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        petType:
          type: string
        color:
          type: string
        age:
          type: integer